VERSION 2.00
Begin Form FMeyesign 
   Caption         =   "Eye Sign Maintenance/Enquiry"
   ClientHeight    =   4020
   ClientLeft      =   1095
   ClientTop       =   1485
   ClientWidth     =   7365
   Height          =   4425
   Left            =   1035
   LinkTopic       =   "Form1"
   ScaleHeight     =   4020
   ScaleWidth      =   7365
   Top             =   1140
   Width           =   7485
End
Option Explicit

