echo on
h:
cd \
cd dev_vb
cd rp
copy all.rp_ a:\all.rp_ /y
copy bloodl.rp_ a:\bloodl.rp_ /y
copy bloodlin.rp_ a:\bloodlin.rp_ /y
copy breeder.rp_ a:\breeder.rp_ /y
copy breederA.rp_ a:\breederA.rp_ /y
copy breederl.rp_ a:\breederl.rp_ /y
copy brnotes.rp_ a:\brnotes.rp_ /y
copy cage.rp_ a:\cage.rp_ /y
copy colour.rp_ a:\colour.rp_ /y
copy con50916.rp_ a:\con50916.rp_ /y
copy conshort.rp_ a:\conshort.rp_ /y
copy distance.rp_ a:\distance.rp_ /y
copy eyesign.rp_ a:\eyesign.rp_ /y
copy fstruc1.rp_ a:\fstruc1.rp_ /y
copy genstock.rp_ a:\genstock.rp_ /y
copy genrace.rp_ a:\genrace.rp_ /y
copy kpi.rp_ a:\kpi.rp_ /y
copy main.rp_ a:\main.rp_ /y
copy master.rp_ a:\master.rp_ /y
copy pedg.rp_ a:\pedg.rp_ /y
copy pedg4.rp_ a:\pedg4.rp_ /y
copy point.rp_ a:\point.rp_ /y
copy races1.rp_ a:\races1.rp_ /y
copy racelst1.rp_ a:\racelst1.rp_ /y
copy ratings.rp_ a:\ratings.rp_ /y
copy results1.rp_ a:\results1.rp_ /y
copy rp.ex_ a:\rp.ex_ /y
copy empty\rpempty.md_ a:\rp.md_ /y
copy salerp.rp_ a:\salerp.rp_ /y
copy salebp.rp_ a:\salebp.rp_ /y
copy salefp.rp_ a:\salefp.rp_ /y
copy team.rp_ a:\team.rp_ /y
copy teamcode.rp_ a:\teamcode.rp_ /y
copy teaml.rp_ a:\teaml.rp_ /y
copy teamp.rp_ a:\teamp.rp_ /y
rem copy teams.rp_ a:\teams.rp_ /y
copy teaml2.rp_ a:\teaml2.rp_ /y
copy teaml3.rp_ a:\teaml3.rp_ /y
copy teaml4.rp_ a:\teaml4.rp_ /y
copy teaml5.rp_ a:\teaml5.rp_ /y
copy toss1.rp_ a:\toss1.rp_ /y
pause
